export const FILTER_INGREDIENT = 'FILTER_INGREDIENT';
export const FETCH_DISH='SHOW_DISH';
export const FETCH_DISHES='FETCH_DISHES';
export const FETCH_CATEGORIES='FETCH_CATEGORIES';
export const FETCH_ERROR='FETCH_ERROR';
export const SEARCH_INGREDIENT='SEARCH_INGREDIENT';