export const FETCH_DISH = 'SHOW_DISH';
export const FETCH_DISHES = 'FETCH_DISHES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCHING_DISH = 'FETCHING_DISH';
export const FETCHING = 'FETCHING';
